global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'exporter-metrics'

rule_files:
  - '/etc/prom-conf/alert.rules'

scrape_configs:
- job_name: 'HostsMetrics'
  dns_sd_configs:
  - names:
    - node-exporter
    refresh_interval: 15s
    type: A
    port: 9100

- job_name: 'ContainerMetrics'
  dns_sd_configs:
  - names:
    - ranch-eye
    refresh_interval: 15s
    type: A
    port: 9104

- job_name: 'rancher-api'
  target_groups:
    - targets:
        - 'prometheus-rancher-exporter:9010'

- job_name: 'rabbitmq-api'
  target_groups:
    - targets:
        - 'prometheus-rabbitmq-exporter:9080'

- job_name: 'statsd-api'
  target_groups:
    - targets:
        - 'prometheus-statsd-exporter:9102'

- job_name: 'Prometheus'
  target_groups:
    - targets:
      -  '127.0.0.1:9090'
